version: "3.4"

services:
  blog:
    build:
      context: wordpress
      target: dev
    environment:
      - WP_ADMIN_PASSWORD=wp-pass
      - WP_ADMIN_USER=admin
      - DB_PASS=db-pass
      - WP_ADMIN_EMAIL=example@example.com
      - WP_URL=http://localhost/
      - WP_TITLE=Example
      - WP_DESCRIPTION=test description
    volumes:
      - blog-www-html:/var/www/html
      - ./wordpress/friism:/var/www/html/wp-content/themes/friism
      - php-sock:/run/php-sock
      - mariadb-sock:/run/mariadb-sock
    depends_on:
      - db
  nginx:
    build:
      context: nginx
      target: dev
    ports:
      - "80:80"
    depends_on:
      - blog
    volumes:
      - blog-www-html:/var/www/html:ro
      - ./wordpress/friism:/var/www/html/wp-content/themes/friism
      - php-sock:/run/php-sock
  db:
    image: jbergstroem/mariadb-alpine
    command: --skip-networking=TRUE
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=db-pass
      - MYSQL_DATABASE=db
      - MARIADB_ROOT_HOST=localhost
    volumes:
      - blog-db-data:/var/lib/mysql
      - mariadb-sock:/run/mysqld
volumes:
  blog-www-html:
    external: true
  blog-db-data:
    external: true
  php-sock:
  mariadb-sock:
