version: "3.4"

services:
  blog:
    build:
      context: wordpress
      target: dev
    environment:
      - WP_ADMIN_PASSWORD=wp-pass
      - DB_PASS=db-pass
      - WP_ADMIN_EMAIL=example@example.com
      - WP_URL=http://localhost/
      - WP_TITLE=Example
    volumes:
      - blog-www-html:/var/www/html
      - ./wordpress/friism:/var/www/html/wp-content/themes/friism
    depends_on:
      - db
    restart: on-failure
  nginx:
    build:
      context: nginx
      target: dev
    ports:
      - "80:80"
    depends_on:
      - blog
    volumes:
      - blog-www-html:/var/www/html:ro
      - ./wordpress/friism:/var/www/html/wp-content/themes/friism
    restart: always
  db:
    image: mariadb:10.4
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=db-pass
      - MYSQL_DATABASE=db
    volumes:
      - blog-db-data:/var/lib/mysql
    restart: always

volumes:
  blog-www-html:
    external: true
  blog-db-data:
    external: true
