version: "3.4"

services:
  blog:
    build:
      context: wordpress
      target: prod
    volumes:
      - blog-www-html:/var/www/html
    depends_on:
      - db
  nginx:
    build: nginx
    ports:
      - "80:80"
    depends_on:
      - blog
    volumes:
      - blog-www-html:/var/www/html
  db:
    image: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=Passw0rd
      - MYSQL_DATABASE=db
    volumes:
      - blog-db-data:/var/lib/mysql

volumes:
  blog-www-html:
    external: true
  blog-db-data:
    external: true
