version: "3.4"

services:
  blog:
    build:
      context: wordpress
      target: prod
    environment:
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
    volumes:
      - blog-www-html:/var/www/html
      - blog-uploads:/var/www/html/wp-content/uploads
    depends_on:
      - db
    restart: on-failure
  nginx:
    build:
      context: nginx
      target: prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - blog
    volumes:
      - blog-www-html:/var/www/html:ro
      - blog-uploads:/var/www/html/wp-content/uploads:ro
      - letsencrypt-certs:/etc/letsencrypt:ro
      - letsencrypt-challenge:/data/letsencrypt:ro
    restart: always
  db:
    build:
      context: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=db
    volumes:
      - blog-db-data:/var/lib/mysql
    restart: always

volumes:
  blog-www-html:
  blog-uploads:
    external: true
  blog-db-data:
    external: true
  letsencrypt-certs:
    external: true
  letsencrypt-challenge:
    external: true
